default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: kangudb
  password: k4ngud4t4b4s3

development:
  <<: *default
  database: Kangu_development

test:
  <<: *default
  database: Kangu_test

production:
  <<: *default
  database: Kangu_production
  username: kangudb
  password: k4ngud4t4b4s3