default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: frepi_pg
  password: Frepi_pg7

development:
  <<: *default
  database: Frepi_development

test:
  <<: *default
  database: Frepi_test

production:
  <<: *default
  database: Frepi_production
  username: frepi_pg
  password: Frepi_pg7