#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:         &development_defaults
  key:               1234567890ABCDEF1234567890ABCDEF
  iv:                1234567890ABCDEF
  cipher_name:       aes-128-cbc
  encoding:          :base64strict
  always_add_header: true

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA4fV52cwNR9+kwGxmXB3F1UN4uFvL5kQ0+Y9ClLCROLEye41v
    vI2SAHkDS0cff1Qcl+qFz4ESVCSQo+jFmaRyS42KrbINuNu40+OzMqDlMk5GJBXa
    g3ceTe4YnfLlVhycoBXlQqhq+1OeIH6s6BQaWuaXO5HkCWqPiT3IZKHR8eSp9hJ+
    3j2mtFyk7bPuUHi0J4wzZC9MZqZRQLAvGGjmCkL0xVJxh1RL40d+wGZjceiyFuSN
    ZRJNDKTVbqpMqqay36rtU8/ksiOeFnPPYoGOuy/lRMrrSLirq/OVKl9IDYjOuwlg
    ZwS51LY/sMMaUMHnflWa1XeqtM0caHPYJgCuiQIDAQABAoIBAA7t0xEqxC3dftsf
    zluDtBB1FsLHfd9G3mEmr/V2/QFL49P58kn46I6TcD5HArO88O6wlgqxsm5QxCWw
    OW3/SXXociMrwnBWRA3r22ka7Em4ljXII9nPwvbPJl05MSHRXh/Nkoom6nqUebwX
    4oCq41riJVfQOcrNeZJNvLG5Z0+d9jLbhSDQjNz1KhcUgmeXfsm6nIz5g4qxrKv3
    MVebE4Uw4PAQkXIAIm09w4Z4jNP61ABf+PIcAaL+s4DVNY7yo2VL0j+lZZZndbfw
    kxsL7JK7bsTxK+j9fO6bIZkeOQlgva1hgm2igpu3CMi2ULi41lmimBPKSf5zpjvC
    Z6tJl0kCgYEA/KlryaPoQqw0Ya1xJ4qpzAJ01koVnOFg7mIL/w/3k3le0RVbPOO3
    DCUtZflEKJyn2Pqwr2dh5rD7tAQSIIVAxCgtv+0J7IxuKPFtRFLiT8CmNZXu1jIA
    t8sUX7yyUbadpJiNghmxEd8KKIkw/dA3fm8+oyOGb3PUZSL13djI7k8CgYEA5PG8
    0g9Pu+q2cwHpDyHtRfV5X0E8TQKoKHpgtfUGmWD6euVxBthCDpbznzVVWl+AdwOb
    9nZ6nQvTUIFfoNgsNW5Xe/KPRG1NoaPiiPR7rUMjyelGsFWpDvNuvu6w+TN1VJPP
    eo3VPO9O4lBrH8BrP6U0bXG2tooRY3iJPqpR96cCgYAcKp7ziaw40o28XeOBbvni
    3ls8EGI8bPurV47SzmrhK+SgFmtnbFNZrUNUXOd2R5CGpdvQkgvd9dj5hoKm0XQY
    6gm/naM/laAqPE/cEAlerrFYw/AuPMDLvH329khCx8LnOIJ+AHM29NBjGHg3s2Cc
    XbZz5V/1SMpiw/T42FP+DQKBgQDEqmfiJmb+7NPHnYd/iUxSgVi+m8JaAQNEqkNz
    asU9clIYygm6sICmGcOzKtRkKo+nLMGICSSwzVy71ja4a5omV9/syGOLiz1ZsfdC
    YInxPzB6HNqtVRhBkJm8iDwcBbkvaz2acEYR7xxbSmuLPfajGJ4ducYTrizbvspe
    u15oFwKBgQDFv+BC7N8TvIOnbiI9h/oAoxfAXMTdbgLDhULPNO3IQm2558+m80G9
    P1xP+lsPI9foWo9XTbgJo4GlWx1PysNy+427vbUwheU4bYbPEVMSptmcryIztQzM
    GpEadmDwM1DcKAdtx2n5X9yKLxkcGBG0KR6qxE1FoPeOoqicGzbmTg==
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename:      ..\keys\kangu_server_release.key
      iv_filename:       ..\keys\kangu_server_release.iv
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEA1xHSI3Nbl2ACCh6ICrGvKbprQC1Py5B4WwKibhDg9joUfxBx
    QrUeSejowE6gLdBQJ8wxjo0TE+mSPi6Ql9+rAQgLGkYXvgTw8w0Lf0aYOoIy5Q3C
    dZRt4ltZQLgVPjYK68X9WbsbzVV+FYfkkmezygAN/OnWThRWmhrvEs3M606ArKG5
    yoHI0clukgbkCo34iRm4KWsBffUjWVY7ssyPzFLzhE4bIo1i9qlSjuI+MyLx3Gfz
    vBhlsPX5gk2J7e2GuxCLETqBAmqwSKKTmRFiTqa2qXaqhTqk2pYLQ/dk1K0ylMJS
    kpbovrwZ8DKQqHS1N4o7+9LPzzCe4+qU0EuktQIDAQABAoIBAAo7cNH69QqYqMAu
    f65ykbDci6m7/iXjM7aww2WVK/7K+Jqq/5h64XwGtrwfgYNse8PI9Tqg/51c6XZH
    5N006P/dkBmp6AtEVOpbXoappyhxdVZsdyn869VvHynzGB+jlpVtEAaq3kHApYUE
    uB03Ddi4c/HqdiW01gHy8hjk7bDsLt6HX/89UfY1bz660lQw4hrYatTWW5st3Dxg
    1rCOpgNRTjUH6DwL2dBM94AXZPt97hdQOYtuhrumkMDMAZNbfozmf/lR4NhgxaGo
    KuFlDK/uav1eQqiRri/PpV8Gjd3nopPHSC/lx5okw7VszeO1HpHDu8vNjlyuZELI
    E/a2QEECgYEA9GABVVtF9tCE1+HOi4vvKnNm48ipClCCjvSgrgt39qJ2qD7y4c/r
    KM06jt8Qa/NEIlukm99SLMbBsDfqBBJONrKOYb/ex9KEkXtQK8wG1QMAMkUWwqRU
    ev/BwDD3menXHcLOYtEIZshvdDUMPQIwpEF9i63Xhb3ubtory5O5py0CgYEA4Uzv
    VUblBRy9fY0S+8xa9oCOEtaPrniy1Txj2rd6J7LdpY6/c3TIK7L5iU5e86zUVeMY
    /T91FxLSOJf/KUwETtnzjqYaBtYb0MSiqLLwG5VJ/hZv/va1/RFcKQcurszTviqi
    /COXanyXX8NRZ84V5q/ob1D9kx7Tbylo2B1aaKkCgYAtktHs1y6/DrgXgpcAU0Jx
    CkB/7mYH9GfEvT5R9vWSW04BpmupTRsv6sYm6tanKyDjv299WjJ7Az4P3P2ZcMiB
    Tt9av2uOnGX4s6SJ5mzHwN2CgnvyJK9UmOnLK9ahL4jclf3jU9RbRrnyVApKPmRP
    3Z7KM8tjt74Fkk5kktImqQKBgC0NRlqGF6vDCH0/pYkmXxYltMM9lnOr/Q64ybrl
    r46arMm7VrtOoexjGJUFT+VoLPmTtN6HPvHDOLhKZKKsabwexx5CRrgRPnSrrV8Q
    kQTjAG3HrNOOH+wf+Y7WudYIbVr8iaTjtRZ9HYPvuaqJQkXj7RW9W0d9BYiX/jgg
    /oApAoGAevpTEmZx91zmuu90SMaEj80xIo4d20cflSQot1lvKoO03Ks6k0TEeQlY
    MrkTQy0tWDCfqxI8cd+pg48G9l5GEklMRUP/v8e6gzUwcHUljuCKR/sqbIw+cezc
    Ay6IigxdUuNUccWJaFDyhbmF4N8ldEibAPr0ctsraonbimXP5Lo=
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename:      ..\keys\kangu_server_production.key
      iv_filename:       ..\keys\kangu_server_production.iv
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true
