#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:         &development_defaults
  key:               1234567890ABCDEF1234567890ABCDEF
  iv:                1234567890ABCDEF
  cipher_name:       aes-128-cbc
  encoding:          :base64strict
  always_add_header: true

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpgIBAAKCAQEAq99UzGtWzHho5hqySm+OgfJWcvvjDWvsqaQL5oqPORGvT1MA
    lLvLzcYaovC74ZjzD2cK9homQL2EGZE5TYpwncht2816TntC7jx6h8H4XRF45YfV
    CiNERIQA6XTuSfEPnE+3VJ0m96DGJjYiQ2bKdxS91ueM7ggLEvm5VaIyUUPhYsjj
    FEj5lv5LwTIitqxhDoQTqFPh7Mw6Td0ZDVuRXciMgUd2mlaD67v0GLOLAHtyovz/
    DSmfsJfHQmOZBqfSse6+5c11d5nGASCFjSDylhHH6AhmdvHdUxyl4VBSlko/anwU
    2Y1kn2rNZqymCLqK1DsSNn9f8g+K3amok1KcRwIDAQABAoIBAQCj/zfkzk9GT2aY
    mcSh7gxmxhvjH6IpPl/WBugsFO5QoCVNZX/aa88uC+eCrn435z+V5Na6uXzirXMN
    CltJN935UDQzVb9sf4T/2cl5HIamF3PqYE/RmpEbZ3GPUbnF6DTjC9V88W8rPceU
    0najJcPvGGWEV/FLd3VJp+tGYLvueWyO6ECduiC6HczoI4S3GoBu/lROPv+N5puO
    yotP5yMxyEBVm69yL+e0WkKI4Y5eh+y526oHg7alR7Nmcjs+EhoxB42IyL58l3C2
    +XS6fzWQtU3oFq6r4Ojkw7r4YiDt8Xx3QQLkpv9S/e0mhgU+rUBT8czv3gsDJ9wW
    9Dm6dVcBAoGBANT2yPVoicLGcsxmS75luNteLtzegI6EKkPIs3MnB2rW9FWw2v8s
    /TFxSRrcT4rR61Q12GagA5eObbJqVvgfPrmeehj8BZwRgX/ZdDjx+RAjkTLeEhmD
    BVXFrhO1/R1KZFd0OG3oDfzzuX4MMS1f2h/sPTRNy9Qkm6Uyu0C0444HAoGBAM6a
    w3+B7hoyulFfwvormlZRVnxnnExSo+fXpMOFOxNjfE/o2NlTfswJqlLhvNz7t5Pi
    wWVECCFUpboZy/03oGl06b57jwwIhyDJCmqSm7apHipVRuVL08A2LLg5d/cDdg3q
    mWIg3ws1cWW8gcsGBjk8VL/cr6t3kepwDaehdO/BAoGBAIs2e6141b0ebsLRCCiB
    ZHL6QVYemRkQqnQ/CZd35vBfbb9qae4vIaAldu15IQIVMWmN/VUwushi0bC0tP9j
    pWQ/hX85mA0qoGXL556mBvMW3P7MjjZhIKauH5pA+CIilC9bCNxHuoUlaZdNLwSD
    SRpfGq9LP7gA6kH2RNQKq0oXAoGBAKf2G58qYwa7XMtQ3bMCBavM3lGu7dsCiCuw
    HUuyoW9GvsY8Fya/AWMhLG3LBP5mST0Z6H3KDA4EweKEnFjUgz2YhXqM+qMev7RA
    nI49eAfMfzCNOWCp/5DQuhRe7A9NqgjwQxgKfymenfzGfoIt+JtJV+DOqaXtRBvi
    UseHtAhBAoGBALyPXZ6xsgm8T72TyfE/HuveCoMonzgCWk7v3Q6Jnr6k/7J3nsfM
    dnh5gCG13/+7niujblClLr26H1yOp9VZeNJ8/To+KgXrHZZ8S4MgCFkCrTSAsyDy
    E8aljUeyUO60ZTprSTXc8eXUkiUxijkvwBc+TV9E/GlPW8ksBX8FMpFm
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename:      /etc/rails/keys/frepi_server_release.key
      iv_filename:       /etc/rails/keys/frepi_server_release.iv
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAzDkixJ9zkv5+eNGNy2NE8GG08nQDjwb+Uchbfv5PlvJV7LhE
    +Nmqisxdg5SEsFHDxwAPTjP8liIDYpZTO7twAJb6plP6jZ+o1hy0yP69wYBgEsyp
    2whCapf3uTaUn4jpO3Mseq9nKYXdGvT+/XennnY1K7X59qp5RkS8TUsF6aZcpKAz
    hJ6Dgnzv9VW2QZGCR6o2RVaMBBYhZ3WuYECBZAkNrYkrKm9f6ENW9b+qxOlxz99o
    nmdDdYHW4+s5lwV8xgLiNpk58gDKh8oFlUfWh2qClDXYsIs2zZaffPPX/zPzaQ/R
    J2bh+7j70QadbrlsV4qSfURmnL9hItE6W6tEfQIDAQABAoIBAH4904A4EPmM2CFX
    aI+RjcwKmhBGJu0DJbLoZ6bZDdoBc5whTIGIDCRAsI3mAR/9a0hYgR2WhU1JOU54
    HnuOIm465jZrMzbYu0Wf+SFGV4aGFN2KJnV/ZY7+4eNcGgOEXqihSZ2NT/gbB9Li
    H74PeU47RCMBGsOgHdeSJdShy8XiNiJLVi0NdlWBvh8byBOGsGHD3m+zCk9hqocH
    Vt0+hmy4jrecvvf0dgR9kre5CYf/Jd8SsPk9JqldOfQ8fhSrJ/xJ25GdrtefJHcy
    nVxkpryVLpt+DMqSGgXltsIDb/T0nC6dao4/+R2n++5+SNXNEQMR3bvMikrC4rGg
    pWEV1wECgYEA6Y7l5g3g3e1zvdTjPG4dQk+zKtpBsi5Cj4yr9uKqILPjD/U2WDoO
    19LjNEoOC/9G8ykV9B4XeHyC1CT4hZqXGUV+3ITofEahr6MohDLPn6IVMhLdeA+b
    r8o1SzoFITnX4HpZKW5ME3k4NdoayznUmTamJLbt3oGkqe3XPVxrc5MCgYEA39im
    iI7H8C31QUmI4EAmk225+bPEaJTXP3/hyxN+SpNw1pdKY/8ECFSLQxeZwFUmc4qG
    OCqv2BNCU4UtBsjPESehzH8uG/e4Glj1ftz/RaZE3VdoTMHnNSsD7bD46ca/DKS+
    lacKlUyBa6LWcQShCm65wc7326ydDqKN3KHbka8CgYEAu+VOZwn7Qg9p8ep29YLQ
    3ywnQ+5as/IrcjkFj5VCsRSHM6tekRQEJPVv+/0n19cDSVRgaQhccX4Z8nnbxgBc
    VuRl7xqtvm1EXnywd8o45oAK9UHgElrcMUxIG8ENp3FVjy5e1Mn7Qh9fbVOOArj/
    pFMmzpqsOzmpM1w4sRDNESkCgYA57LdTeRc2CL6BcYTw+sjAt9E7U5CMu49jyDTm
    txmkNLkrXqUKcVBa033iE7ZeteooVf1bhXhRgtJUCI9ZRReISegtoe+NnzHN551H
    geqw3FDPsjG0Qy0QbhwrIvOWky6XF/6VfU9YyR5oew/g2SDPMU3yYBt1hhpyUhBB
    usS10wKBgEHmFDwVe92lruvxClLad1dpfgdNrx8s09iX5Y7nV2kLXN1Af6UIk2I6
    UmRA2QOrQIjrCafPIfEIWHfA0ygqKS2M7PraAN4NY5r4kpWMA48MqXkgUM85Zbro
    aORIoNe5XWHCfAFknHJp5lDsdubPqtereVIrcIvdYzXtONy6wN9V
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename:      /etc/rails/keys/frepi_server_production.key
      iv_filename:       /etc/rails/keys/frepi_server_production.iv
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true
