#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:         &development_defaults
  key:               1234567890ABCDEF
  iv:                1234567890ABCDEF
  cipher_name:       aes-128-cbc
  encoding:          :base64strict
  always_add_header: true

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAqF+pOVPs7/CnAZZshqUsRT+Ky8eCx5mR3iCnJqabeckzFccI
    uqi716WIX56xIo4Xp17ggy0k3i//el6+GgHLPoaXhDr3UpGWEog/xRoE0ovov9jJ
    Bc7PTF8ta1uwz1TufU1q5tfJAa4ol50/xc6KUXdKN3o8b+E1wmo6O8+ZgOx5qXCS
    iGwC9czqApYpdCKO21w24G0/K62rOkzVgjlJziQQxxwfJbnHBb57pjzXRw0idAPi
    dLNJNvLbv6uL9dClwvpLcQzjzQWdTRsJES7aViiec8VwQRzxdu1OfWlhFaQJM9T/
    M2Y5+EdrGz6k+ZOL10AnUzYnAtWw/VKPYUjZqQIDAQABAoIBAGdzl1sk6MCoIUTF
    ctrr456Moy//3qfbAJf1gh4qYf7bE2s/BmsBv6CJEZiGvZlYqsnobpPKiguGfDdo
    vO7nyUQamD/jpxBxaT7rvhrRmMLwucoeXa0W26G2HQcIqENLkNkmVxeM3/ELW9+D
    +6oC9FOHsu8RSM8JFenlMPCM5mkiYyn33DDWzVWXPYF/7mt2981IWg7C+BPu+7vZ
    t2p5046U0ZZjRPwp5RESIUpH1DC1zIE+xpOPMQGQ3GI4QxGoeOv61ao5Jvdc+nyX
    HQFCfI009LSSfDAlFt2OfEg9lTPqxNUTzLuc27bjMPCBXJ2h3hbjMOXHT/GBMFlu
    U/pjbIECgYEA3JHLi7icEyAknIoonbe7cIQxpmP0QomrT275PK/wWK9P6MYzKeb6
    4k9I2WXPjBSOMJJ7tfu2CBwOSi6HLelKazD97VhZTmfmN5tQ4pgfzBSF+7ITWEVp
    CjsWv20zCHup9x1vGtpeqByguNYlli0qgJSMae3dPh28JMSZG/vSPpECgYEAw2t7
    TqkWoCCYw51bMSuBT1sP/nVowCqrxuuU+5kAckWQH3bK94zWHbpClIxrCkh5Wu09
    o4dQeKIwYgSq53/8qP+NuQjikjTjXr33iHwtYEibN5CTcGTSw0cR2BnLQ0mpc7V3
    cki7O3+dAi+4ynLHQIt7UVysm9yKqzX0XrxupZkCgYEAhkJot7/DoRCruG2Qk5BH
    FBIjdrjY8beDA3L1Wy9tCU6NQY+DjTn/9Ml1+n6yev34HzDLBNcW0pDhUd5IgnXC
    ysSjjFl+4u7zf12XOpaGpF7Jv4+BnvWBHq0hB5yct8kuiDDudFX/0Cy82EXh0yvi
    9yl03vXe+fR3lZnl6Na7/0ECgYBukOl7YAAFKWxFgUqPT2YiWAt8lUFnOL1oFvJ8
    R90Qynr40mWUGoMq3q+9DJWjg83lvEUbuPu2xU1KqAlqYee6Vp0BDB3lSzc565Ga
    D2g9CdeIYKyK8wCsrBFUi4ON1qehaBLk/nGxAEr9abLMGJTT2Bc1uZGPvgBXTnet
    AkA4QQKBgDXJ6G9sfrmrcYU2rlttw+XyoaUEO2NtzY9IVtf5bfcVBufvpg8+Bqww
    zpXKyiZSMQ7YFiW4bEYl48dMR7yBSF3Mvu5PmW2sxfieSX30/IN2D8SWuHraBSRX
    iWi+37tBM7kozIIw3jIox3ZvC4C428cDPZj+184rk9IqrDAxv3qC
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename:      /etc/rails/keys/kangu_server_release.key
      iv_filename:       /etc/rails/keys/kangu_server_release.iv
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEAtO70FTuAdH0OAwl5sCRZhKqMEjE+0k33U8n41pX8ymSYHr2r
    dgkWezy5sHo0GVGg62CzAvj/MIs4SyzEStKssEYmF5PKMFnTHmnuttBSIdLlZOZD
    M6Osm8eZrTWYjMiue0Jcol4LSjvEeYoZoePmLokSghZRrvcjj5+cfZPOg5yT0FWO
    14pFlZi/R4qiyV55cJbeSyVRg24o5AUnDSQ504Y59+DXtZnVDi/EQIPGqGiqG8p0
    buQf60PdJ7cCGNoERk1+asJmAARgBmFhdZw3g6vUq2C6ltBMxcZlTewwZvUS0YYM
    vShObEdxp72rStFffG3XcdUfnRii4mdhS1jy4QIDAQABAoIBACpoi7tiS/SBz0P0
    95nKm1TWKKim9EOU1LDF+VZKp4rE00b5S/QJo0RVcmyj6Aw7Ls2cx7idpiq5pwMv
    xf6HrMRQXONP16dHlo1dZP9iiq204eGpevzikzWcLjAEDPKKoyLu5gmEo37NzXpz
    XRit8yjbJgRpuNGaybIDRknE2DXOmw3ZFC+E+VCCvEbLfim7f//PWHmGSNCF9xIJ
    8wDRC5IMyuxYgXsVhf7psPVtS68e6euxUtEGQRmJDisfJIM731lnmV3aEKEzQJ3H
    alQGO3oqo3+NjP0v38Uc0eVEZLOeFYHHs5YD9HdtLsonCj+xnvMZXGHnU8E4oXXE
    FdRykDECgYEA7dYX5Ko+4VAJ73Ag0pCQmHKwIth38q5rLTGXOsi3CFABy4twV9+p
    BMaAx0Q5IB7PB7pr9FAz+gUDIoCYjuHUGxvfez36o4eO7JJWMIR5FaCycpg8bMas
    UteOCZVZTSRr1VAhWKd8L8UQl0iqGWPjPOEj+qt29Tc8HFcoUV5B45UCgYEAwsBb
    7cu/iXHN3H+bMbY35KLrCzpvVeLH9eFxUm5jwRYNPVMROaFk3xJgJT9iDBLuZQ68
    s9gTJ/xy5b8+2qKgV03Pxsm6xOY4ZC/lyrU7Vs9S0PKcGpIdD5AMvovjd2Infpp8
    /ur3Us9iWLloH9jmZEHKB4SG5ujpw2qsNjs+vx0CgYEAxSIMoeMexYCjC4ykGAPt
    Zf7B0dAc89DwUwBkuju9wi0Wn9DO6HchUCz8dq4sr1v5/AzgCBwmSNi4tXNjgCLc
    vS+IOE2yHrNwmtPcjtBu0Kdm4acfhoXSNcQnHfhlkZRbsO5/BU2lmK69xrdbDjqG
    EmMGgHJ44l3K/C6d43u+H1UCgYEApZErlkp1l7/sp9zEb8reUb4/3Nfc90NJhDwZ
    P18h53F75/rK1hfjzdGtc30jOeiOS9PvkWXNQ11XwQKJyQ4hCpfYYMP3yJWAs4wU
    6/SPcgnn+kOHev9lPWnVq9j5lPEZaoSkZ4QSp5AvqAZYA1s+41UbELEWjxDMS5pQ
    tfpAKfECgYEA1wr3BuKZAu7raagZyLG1pkW/MpgA6O2WTnq1JKyZhLJb+a4w8Wkg
    7jE8ieArQvHqDVOG51V58qawmrShG/i8Z8/qlppo+v/7bbxGEWJ5sjALlgAoYQTs
    44zMU6Ir2Jap2fQj/dvYm7sP78E+kUVHV0QwkiGZz/AO7ES4QoTI8Dw=
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename:      /etc/rails/keys/kangu_server_production.key
      iv_filename:       /etc/rails/keys/kangu_server_production.iv
      #key:               1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ
      #iv:                1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true
