class Constants

	# Paginations
	ITEMS_PER_PAGE = 20

	# Paymodes
	PAY_MODE_CASH = 0
	PAY_MODE_CREDIT_BUSINESS = 1
	CREDIT_EXTRA_DAY = 20
	CREDIT_INTEREST_PERCENT = 3

	# Charges
	USER_HOME = 501
	KANGU_ADMIN = 101
	KANGU_SUPERVISOR = 102
	KANGU_PROVIDER = 201
	BUSINESS_OWNER = 301
	BUSINESS_ADMIN = 302
	BUSINESS_CHEF = 303
	BUSINESS_OPERATOR = 304

	# Measurement type
	MEASUREMENT_LT = 0
	MEASUREMENT_KG = 1

	#Income-Expenses
	MOV_TYPE_INCOME = 0
	MOV_TYPE_EXPENSES = 1
	SOURCE_TYPE_OTHER = 0
	THIRD_TYPE_BUSINESS = 0
	THIRD_TYPE_PERSON = 1

end